#!/srvr/cs3311psql/lib/php525/bin/php
<?php


define("LIB_DIR","/import/adams/1/cs3311/public_html/19s1/assignments/a2");
require_once(LIB_DIR."/db.php");

define("DB_CONNECTION","dbname=a2");



if ($argc < 2 || is_numeric($argv[1])) exit("Usage: ./acting <Name>\n");
$name = $argv[1];

$db = dbConnect("dbname=a2");


$qry = <<<_SQL_
select m.title, d.name, m.year, m.content_rating, r.imdb_score
from Acting ac, Actor ao, Rating r,
Movie m left join Director d on (m.director_id = d.id)
where  ao.name ~* %s
and ao.id = ac.actor_id
and m.id = ac.movie_id
and m.id = r.movie_id
order by m.year, m.title
_SQL_;

$res = dbQuery($db, mkSQL($qry, $name));
$count = dbNResults($res);  // Count the number of new line
if($count==0) return;
$c = 0;                     // Count the tuples

while ($i = dbNext($res)) {    
    if($c!=$count-1){
        printf("%s. %s ",++$c,$i[0]); 
        
        if($i[1]!=NULL) {
            printf("-- %s (", $i[1]);
            
        } else {
            echo "(";
        }
        $n = array($i[2],$i[3],$i[4]);
        $n = array_filter($n);
        $n = implode(', ', $n);
        echo $n;
            
        echo ")\n";
    } else {
        printf("%s. %s ",++$c,$i[0]); 
        
        if($i[1]!=NULL) {
            printf("-- %s (", $i[1]);
            
        } else {
            echo "(";
        }
        $n = array($i[2],$i[3],$i[4]);
        $n = array_filter($n);
        $n = implode(', ', $n);echo $n;
            
        echo")";
    }
}
?>

